### ISSUE TITLE
How to find generated RUST code?

### ISSUE THREAD

**Issue by qiluge** [saber-hq/anchor-gen#72]
I use anchor-gen in new crates:
<img width="806" alt="image" src="https://github.com/saber-hq/anchor-gen/assets/19525062/087078a2-5246-493c-aaa8-e19cda817a8c">
And used in other crates:
<img width="799" alt="image" src="https://github.com/saber-hq/anchor-gen/assets/19525062/cf14cc2c-8fea-4fca-a872-f24225817d65">
But I cannot see the structure field. So, what is detail of generated code?

**Comment by macalinao** [comment]
let me know if you still need help!

**Comment by qiluge** [comment]
the trait `BorshSerialize` is not implemented for `ix_accounts::OpenPositionBumps`
<img width="1296" alt="image" src="https://github.com/saber-hq/anchor-gen/assets/19525062/f918d824-950c-47a8-bf32-052a5241a2c1">
When I generate from jupiter IDL, it's normal, but failed for whirlpool.json. The difference of jupiter.json and whirlpool.json is instruction args. Jupiter.json doesn't contain args but whirlpool.json own.

jupiter IDL
<img width="374" alt="image" src="https://github.com/saber-hq/anchor-gen/assets/19525062/3d1d1ad7-a713-4982-8abc-7f3a667135c2">

whirlpool IDL
<img width="395" alt="image" src="https://github.com/saber-hq/anchor-gen/assets/19525062/9539aacc-4488-4fac-b35e-dc82f28e9ec2">

**Comment by qiluge** [comment]
my anchor-lang version is 0.29.0. When I change it to 0.26.0, the error changed:
![image](https://github.com/saber-hq/anchor-gen/assets/19525062/eefbe3c1-06f4-4c23-8f54-3f87e77adc42)
